apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  {{- if .Values.appSelector.labels }}
  labels:
    {{- .Values.appSelector.labels | toYaml | nindent 4 }}
    {{- if .Values.additionalLabels }}
      {{- .Values.additionalLabels | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  NOTIFY_AUTHORIZATION_JWT_SECRET: {{ .Values.settings.notify.authorization.jwt.secret | b64enc | quote }}
  NOTIFY_AUTHORIZATION_JWT_ISSUER: {{ .Values.settings.notify.authorization.jwt.issuer | b64enc | quote }}
  NOTIFY_AUTHORIZATION_JWT_AUDIENCE: {{ .Values.settings.notify.authorization.jwt.audience | b64enc | quote }}
  NOTIFY_AUTHORIZATION_JWT_USERID: {{ .Values.settings.notify.authorization.jwt.userId | b64enc | quote }}
  NOTIFY_AUTHORIZATION_JWT_USERNAME: {{ .Values.settings.notify.authorization.jwt.userName | b64enc | quote }}
  USER_AUTHORIZATION_JWT_SECRET: {{ .Values.settings.user.authorization.jwt.secret | b64enc | quote }}
  USER_AUTHORIZATION_JWT_ISSUER: {{ .Values.settings.user.authorization.jwt.issuer | b64enc | quote }}
  USER_AUTHORIZATION_JWT_AUDIENCE: {{ .Values.settings.user.authorization.jwt.audience | b64enc | quote }}
  USER_AUTHORIZATION_JWT_USERID: {{ .Values.settings.user.authorization.jwt.userId | b64enc | quote }}
  USER_AUTHORIZATION_JWT_USERNAME: {{ .Values.settings.user.authorization.jwt.userName | b64enc | quote }}
  USER_AUTHORIZATION_KEY_NOTIFYNL: {{ .Values.settings.user.authorization.key.notifyNl | b64enc | quote }}
  USER_AUTHORIZATION_KEY_OBJECTEN: {{ .Values.settings.user.authorization.key.objecten | b64enc | quote }}
