name: Release charts

on:
  push:
    branches:
      - main

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Helm docs 🤖
        uses: losisin/helm-docs-github-action@v1.2.5
        with:
          git-push: true
          git-push-user-name: "${{ github.actor }}"
          git-push-user-email: "${{ github.actor }}@users.noreply.github.com"
          git-commit-message: "🧹 update chart documentation"
      - name: Merge to gh-pages 📖
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: main
          target_branch: gh-pages
          github_token: "${{ secrets.GITHUB_TOKEN }}"
  release:
    if: ${{ always() }}
    needs: [docs]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Configure Git 🧰
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Install Helm ⎈
        uses: azure/setup-helm@v4.1.0
      - name: Prepare GPG 🔒
        run: |
          gpg_dir=.cr-gpg
          mkdir "$gpg_dir"
          keyring="$gpg_dir/secring.gpg"
          base64 -d <<< "$GPG_KEYRING_BASE64" > "$keyring"
          passphrase_file="$gpg_dir/passphrase"
          echo "$GPG_PASSPHRASE" > "$passphrase_file"
          echo "CR_PASSPHRASE_FILE=$passphrase_file" >> "$GITHUB_ENV"
          echo "CR_KEYRING=$keyring" >> "$GITHUB_ENV"
        env:
          GPG_KEYRING_BASE64: "${{ secrets.GPG_KEYRING_BASE64 }}" #Referring secrets of github above
          GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
      - name: Add dependency repos 🔗
        run: |
          helm repo add denhaag https://gemeente-denhaag.github.io/helm-charts/
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
      - name: Chart releaser 🤖
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: "./"
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_KEY: "${{ secrets.CR_KEY }}"
          CR_SIGN: true
