name: Release charts

on:
  push:
    branches:
      - main

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Helm docs 🤖
        uses: losisin/helm-docs-github-action@v1.2.1
        with:
          git-push: true
          git-push-user-name: "${{ github.actor }}"
          git-push-user-email: "${{ github.actor }}@users.noreply.github.com"
          git-commit-message: "🧹 update chart documentation"
  release:
    if: ${{ always() }}
    needs: [docs]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Configure Git 🧰
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"      
      - name: Install Helm ⎈
        uses: azure/setup-helm@v4
      - name: Chart releaser 🤖
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: "./"
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Merge to gh-pages 📖
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: main
          target_branch: gh-pages
          github_token: "${{ secrets.GITHUB_TOKEN }}"